# Nixpacks configuration for Railway deployment
# Optimized for Strapi v5 with PostgreSQL

[variables]
NIXPACKS_NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_18", "npm", "python3", "gcc", "make"]

[phases.install]
cmds = [
  "npm ci --include=dev",
  "npm list --depth=0"
]

[phases.build]
cmds = [
  "NODE_ENV=production npm run build"
]

[start]
cmd = "npm run start"
