/**
 * Nomes de países por idioma — ARQUIVO GERADO, não editar à mão.
 *
 * Gerado por scripts/gerar-nomes-de-paises.js a partir da base de idiomas do
 * Node. O Hermes não implementa Intl.DisplayNames, então sem esta tabela o app
 * mostra siglas no lugar dos nomes e a busca por nome não acha nada.
 */

import { IdiomaSuportado } from './pseudonimo';

export const NOMES_DE_PAISES: Record<IdiomaSuportado, Record<string, string>> = {
  pt: {
    AD: 'Andorra',
    AE: 'Emirados Árabes Unidos',
    AF: 'Afeganistão',
    AG: 'Antígua e Barbuda',
    AI: 'Anguila',
    AL: 'Albânia',
    AM: 'Armênia',
    AO: 'Angola',
    AQ: 'Antártida',
    AR: 'Argentina',
    AS: 'Samoa Americana',
    AT: 'Áustria',
    AU: 'Austrália',
    AW: 'Aruba',
    AX: 'Ilhas Aland',
    AZ: 'Azerbaijão',
    BA: 'Bósnia e Herzegovina',
    BB: 'Barbados',
    BD: 'Bangladesh',
    BE: 'Bélgica',
    BF: 'Burquina Faso',
    BG: 'Bulgária',
    BH: 'Barein',
    BI: 'Burundi',
    BJ: 'Benin',
    BL: 'São Bartolomeu',
    BM: 'Bermudas',
    BN: 'Brunei',
    BO: 'Bolívia',
    BQ: 'Países Baixos Caribenhos',
    BR: 'Brasil',
    BS: 'Bahamas',
    BT: 'Butão',
    BV: 'Ilha Bouvet',
    BW: 'Botsuana',
    BY: 'Bielorrússia',
    BZ: 'Belize',
    CA: 'Canadá',
    CC: 'Ilhas Cocos (Keeling)',
    CD: 'Congo - Kinshasa',
    CF: 'República Centro-Africana',
    CG: 'República do Congo',
    CH: 'Suíça',
    CI: 'Costa do Marfim',
    CK: 'Ilhas Cook',
    CL: 'Chile',
    CM: 'Camarões',
    CN: 'China',
    CO: 'Colômbia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CV: 'Cabo Verde',
    CW: 'Curaçao',
    CX: 'Ilha Christmas',
    CY: 'Chipre',
    CZ: 'Tchéquia',
    DE: 'Alemanha',
    DJ: 'Djibuti',
    DK: 'Dinamarca',
    DM: 'Dominica',
    DO: 'República Dominicana',
    DZ: 'Argélia',
    EC: 'Equador',
    EE: 'Estônia',
    EG: 'Egito',
    EH: 'Saara Ocidental',
    ER: 'Eritreia',
    ES: 'Espanha',
    ET: 'Etiópia',
    FI: 'Finlândia',
    FJ: 'Fiji',
    FK: 'Ilhas Malvinas',
    FM: 'Micronésia',
    FO: 'Ilhas Faroé',
    FR: 'França',
    GA: 'Gabão',
    GB: 'Reino Unido',
    GD: 'Granada',
    GE: 'Geórgia',
    GF: 'Guiana Francesa',
    GG: 'Guernsey',
    GH: 'Gana',
    GI: 'Gibraltar',
    GL: 'Groenlândia',
    GM: 'Gâmbia',
    GN: 'Guiné',
    GP: 'Guadalupe',
    GQ: 'Guiné Equatorial',
    GR: 'Grécia',
    GS: 'Ilhas Geórgia do Sul e Sandwich do Sul',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Guiné-Bissau',
    GY: 'Guiana',
    HK: 'Hong Kong, RAE da China',
    HM: 'Ilhas Heard e McDonald',
    HN: 'Honduras',
    HR: 'Croácia',
    HT: 'Haiti',
    HU: 'Hungria',
    ID: 'Indonésia',
    IE: 'Irlanda',
    IL: 'Israel',
    IM: 'Ilha de Man',
    IN: 'Índia',
    IO: 'Território Britânico do Oceano Índico',
    IQ: 'Iraque',
    IR: 'Irã',
    IS: 'Islândia',
    IT: 'Itália',
    JE: 'Jersey',
    JM: 'Jamaica',
    JO: 'Jordânia',
    JP: 'Japão',
    KE: 'Quênia',
    KG: 'Quirguistão',
    KH: 'Camboja',
    KI: 'Quiribati',
    KM: 'Comores',
    KN: 'São Cristóvão e Névis',
    KP: 'Coreia do Norte',
    KR: 'Coreia do Sul',
    KW: 'Kuwait',
    KY: 'Ilhas Cayman',
    KZ: 'Cazaquistão',
    LA: 'Laos',
    LB: 'Líbano',
    LC: 'Santa Lúcia',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LR: 'Libéria',
    LS: 'Lesoto',
    LT: 'Lituânia',
    LU: 'Luxemburgo',
    LV: 'Letônia',
    LY: 'Líbia',
    MA: 'Marrocos',
    MC: 'Mônaco',
    MD: 'Moldávia',
    ME: 'Montenegro',
    MF: 'São Martinho',
    MG: 'Madagascar',
    MH: 'Ilhas Marshall',
    MK: 'Macedônia do Norte',
    ML: 'Mali',
    MM: 'Mianmar (Birmânia)',
    MN: 'Mongólia',
    MO: 'Macau, RAE da China',
    MP: 'Ilhas Marianas do Norte',
    MQ: 'Martinica',
    MR: 'Mauritânia',
    MS: 'Montserrat',
    MT: 'Malta',
    MU: 'Maurício',
    MV: 'Maldivas',
    MW: 'Malaui',
    MX: 'México',
    MY: 'Malásia',
    MZ: 'Moçambique',
    NA: 'Namíbia',
    NC: 'Nova Caledônia',
    NE: 'Níger',
    NF: 'Ilha Norfolk',
    NG: 'Nigéria',
    NI: 'Nicarágua',
    NL: 'Países Baixos',
    NO: 'Noruega',
    NP: 'Nepal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'Nova Zelândia',
    OM: 'Omã',
    PA: 'Panamá',
    PE: 'Peru',
    PF: 'Polinésia Francesa',
    PG: 'Papua-Nova Guiné',
    PH: 'Filipinas',
    PK: 'Paquistão',
    PL: 'Polônia',
    PM: 'São Pedro e Miquelão',
    PN: 'Ilhas Pitcairn',
    PR: 'Porto Rico',
    PS: 'Territórios palestinos',
    PT: 'Portugal',
    PW: 'Palau',
    PY: 'Paraguai',
    QA: 'Catar',
    RE: 'Reunião',
    RO: 'Romênia',
    RS: 'Sérvia',
    RU: 'Rússia',
    RW: 'Ruanda',
    SA: 'Arábia Saudita',
    SB: 'Ilhas Salomão',
    SC: 'Seicheles',
    SD: 'Sudão',
    SE: 'Suécia',
    SG: 'Singapura',
    SH: 'Santa Helena',
    SI: 'Eslovênia',
    SJ: 'Svalbard e Jan Mayen',
    SK: 'Eslováquia',
    SL: 'Serra Leoa',
    SM: 'San Marino',
    SN: 'Senegal',
    SO: 'Somália',
    SR: 'Suriname',
    SS: 'Sudão do Sul',
    ST: 'São Tomé e Príncipe',
    SV: 'El Salvador',
    SX: 'Sint Maarten',
    SY: 'Síria',
    SZ: 'Essuatíni',
    TC: 'Ilhas Turcas e Caicos',
    TD: 'Chade',
    TF: 'Territórios Franceses do Sul',
    TG: 'Togo',
    TH: 'Tailândia',
    TJ: 'Tadjiquistão',
    TK: 'Tokelau',
    TL: 'Timor-Leste',
    TM: 'Turcomenistão',
    TN: 'Tunísia',
    TO: 'Tonga',
    TR: 'Turquia',
    TT: 'Trinidad e Tobago',
    TV: 'Tuvalu',
    TW: 'Taiwan',
    TZ: 'Tanzânia',
    UA: 'Ucrânia',
    UG: 'Uganda',
    UM: 'Ilhas Menores Distantes dos EUA',
    US: 'Estados Unidos',
    UY: 'Uruguai',
    UZ: 'Uzbequistão',
    VA: 'Cidade do Vaticano',
    VC: 'São Vicente e Granadinas',
    VE: 'Venezuela',
    VG: 'Ilhas Virgens Britânicas',
    VI: 'Ilhas Virgens Americanas',
    VN: 'Vietnã',
    VU: 'Vanuatu',
    WF: 'Wallis e Futuna',
    WS: 'Samoa',
    YE: 'Iêmen',
    YT: 'Mayotte',
    ZA: 'África do Sul',
    ZM: 'Zâmbia',
    ZW: 'Zimbábue',
  },
  en: {
    AD: 'Andorra',
    AE: 'United Arab Emirates',
    AF: 'Afghanistan',
    AG: 'Antigua & Barbuda',
    AI: 'Anguilla',
    AL: 'Albania',
    AM: 'Armenia',
    AO: 'Angola',
    AQ: 'Antarctica',
    AR: 'Argentina',
    AS: 'American Samoa',
    AT: 'Austria',
    AU: 'Australia',
    AW: 'Aruba',
    AX: 'Åland Islands',
    AZ: 'Azerbaijan',
    BA: 'Bosnia & Herzegovina',
    BB: 'Barbados',
    BD: 'Bangladesh',
    BE: 'Belgium',
    BF: 'Burkina Faso',
    BG: 'Bulgaria',
    BH: 'Bahrain',
    BI: 'Burundi',
    BJ: 'Benin',
    BL: 'St. Barthélemy',
    BM: 'Bermuda',
    BN: 'Brunei',
    BO: 'Bolivia',
    BQ: 'Caribbean Netherlands',
    BR: 'Brazil',
    BS: 'Bahamas',
    BT: 'Bhutan',
    BV: 'Bouvet Island',
    BW: 'Botswana',
    BY: 'Belarus',
    BZ: 'Belize',
    CA: 'Canada',
    CC: 'Cocos (Keeling) Islands',
    CD: 'Congo - Kinshasa',
    CF: 'Central African Republic',
    CG: 'Congo - Brazzaville',
    CH: 'Switzerland',
    CI: 'Côte d’Ivoire',
    CK: 'Cook Islands',
    CL: 'Chile',
    CM: 'Cameroon',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CV: 'Cape Verde',
    CW: 'Curaçao',
    CX: 'Christmas Island',
    CY: 'Cyprus',
    CZ: 'Czechia',
    DE: 'Germany',
    DJ: 'Djibouti',
    DK: 'Denmark',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    DZ: 'Algeria',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egypt',
    EH: 'Western Sahara',
    ER: 'Eritrea',
    ES: 'Spain',
    ET: 'Ethiopia',
    FI: 'Finland',
    FJ: 'Fiji',
    FK: 'Falkland Islands',
    FM: 'Micronesia',
    FO: 'Faroe Islands',
    FR: 'France',
    GA: 'Gabon',
    GB: 'United Kingdom',
    GD: 'Grenada',
    GE: 'Georgia',
    GF: 'French Guiana',
    GG: 'Guernsey',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GL: 'Greenland',
    GM: 'Gambia',
    GN: 'Guinea',
    GP: 'Guadeloupe',
    GQ: 'Equatorial Guinea',
    GR: 'Greece',
    GS: 'South Georgia & South Sandwich Islands',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HK: 'Hong Kong SAR China',
    HM: 'Heard & McDonald Islands',
    HN: 'Honduras',
    HR: 'Croatia',
    HT: 'Haiti',
    HU: 'Hungary',
    ID: 'Indonesia',
    IE: 'Ireland',
    IL: 'Israel',
    IM: 'Isle of Man',
    IN: 'India',
    IO: 'British Indian Ocean Territory',
    IQ: 'Iraq',
    IR: 'Iran',
    IS: 'Iceland',
    IT: 'Italy',
    JE: 'Jersey',
    JM: 'Jamaica',
    JO: 'Jordan',
    JP: 'Japan',
    KE: 'Kenya',
    KG: 'Kyrgyzstan',
    KH: 'Cambodia',
    KI: 'Kiribati',
    KM: 'Comoros',
    KN: 'St. Kitts & Nevis',
    KP: 'North Korea',
    KR: 'South Korea',
    KW: 'Kuwait',
    KY: 'Cayman Islands',
    KZ: 'Kazakhstan',
    LA: 'Laos',
    LB: 'Lebanon',
    LC: 'St. Lucia',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesotho',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    LV: 'Latvia',
    LY: 'Libya',
    MA: 'Morocco',
    MC: 'Monaco',
    MD: 'Moldova',
    ME: 'Montenegro',
    MF: 'St. Martin',
    MG: 'Madagascar',
    MH: 'Marshall Islands',
    MK: 'North Macedonia',
    ML: 'Mali',
    MM: 'Myanmar (Burma)',
    MN: 'Mongolia',
    MO: 'Macao SAR China',
    MP: 'Northern Mariana Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MS: 'Montserrat',
    MT: 'Malta',
    MU: 'Mauritius',
    MV: 'Maldives',
    MW: 'Malawi',
    MX: 'Mexico',
    MY: 'Malaysia',
    MZ: 'Mozambique',
    NA: 'Namibia',
    NC: 'New Caledonia',
    NE: 'Niger',
    NF: 'Norfolk Island',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Netherlands',
    NO: 'Norway',
    NP: 'Nepal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'New Zealand',
    OM: 'Oman',
    PA: 'Panama',
    PE: 'Peru',
    PF: 'French Polynesia',
    PG: 'Papua New Guinea',
    PH: 'Philippines',
    PK: 'Pakistan',
    PL: 'Poland',
    PM: 'St. Pierre & Miquelon',
    PN: 'Pitcairn Islands',
    PR: 'Puerto Rico',
    PS: 'Palestinian Territories',
    PT: 'Portugal',
    PW: 'Palau',
    PY: 'Paraguay',
    QA: 'Qatar',
    RE: 'Réunion',
    RO: 'Romania',
    RS: 'Serbia',
    RU: 'Russia',
    RW: 'Rwanda',
    SA: 'Saudi Arabia',
    SB: 'Solomon Islands',
    SC: 'Seychelles',
    SD: 'Sudan',
    SE: 'Sweden',
    SG: 'Singapore',
    SH: 'St. Helena',
    SI: 'Slovenia',
    SJ: 'Svalbard & Jan Mayen',
    SK: 'Slovakia',
    SL: 'Sierra Leone',
    SM: 'San Marino',
    SN: 'Senegal',
    SO: 'Somalia',
    SR: 'Suriname',
    SS: 'South Sudan',
    ST: 'São Tomé & Príncipe',
    SV: 'El Salvador',
    SX: 'Sint Maarten',
    SY: 'Syria',
    SZ: 'Eswatini',
    TC: 'Turks & Caicos Islands',
    TD: 'Chad',
    TF: 'French Southern Territories',
    TG: 'Togo',
    TH: 'Thailand',
    TJ: 'Tajikistan',
    TK: 'Tokelau',
    TL: 'Timor-Leste',
    TM: 'Turkmenistan',
    TN: 'Tunisia',
    TO: 'Tonga',
    TR: 'Türkiye',
    TT: 'Trinidad & Tobago',
    TV: 'Tuvalu',
    TW: 'Taiwan',
    TZ: 'Tanzania',
    UA: 'Ukraine',
    UG: 'Uganda',
    UM: 'U.S. Outlying Islands',
    US: 'United States',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VA: 'Vatican City',
    VC: 'St. Vincent & Grenadines',
    VE: 'Venezuela',
    VG: 'British Virgin Islands',
    VI: 'U.S. Virgin Islands',
    VN: 'Vietnam',
    VU: 'Vanuatu',
    WF: 'Wallis & Futuna',
    WS: 'Samoa',
    YE: 'Yemen',
    YT: 'Mayotte',
    ZA: 'South Africa',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
  },
  es: {
    AD: 'Andorra',
    AE: 'Emiratos Árabes Unidos',
    AF: 'Afganistán',
    AG: 'Antigua y Barbuda',
    AI: 'Anguila',
    AL: 'Albania',
    AM: 'Armenia',
    AO: 'Angola',
    AQ: 'Antártida',
    AR: 'Argentina',
    AS: 'Samoa Americana',
    AT: 'Austria',
    AU: 'Australia',
    AW: 'Aruba',
    AX: 'Islas Aland',
    AZ: 'Azerbaiyán',
    BA: 'Bosnia y Herzegovina',
    BB: 'Barbados',
    BD: 'Bangladés',
    BE: 'Bélgica',
    BF: 'Burkina Faso',
    BG: 'Bulgaria',
    BH: 'Baréin',
    BI: 'Burundi',
    BJ: 'Benín',
    BL: 'San Bartolomé',
    BM: 'Bermudas',
    BN: 'Brunéi',
    BO: 'Bolivia',
    BQ: 'Caribe neerlandés',
    BR: 'Brasil',
    BS: 'Bahamas',
    BT: 'Bután',
    BV: 'Isla Bouvet',
    BW: 'Botsuana',
    BY: 'Bielorrusia',
    BZ: 'Belice',
    CA: 'Canadá',
    CC: 'Islas Cocos',
    CD: 'República Democrática del Congo',
    CF: 'República Centroafricana',
    CG: 'Congo',
    CH: 'Suiza',
    CI: 'Côte d’Ivoire',
    CK: 'Islas Cook',
    CL: 'Chile',
    CM: 'Camerún',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CV: 'Cabo Verde',
    CW: 'Curazao',
    CX: 'Isla de Navidad',
    CY: 'Chipre',
    CZ: 'Chequia',
    DE: 'Alemania',
    DJ: 'Yibuti',
    DK: 'Dinamarca',
    DM: 'Dominica',
    DO: 'República Dominicana',
    DZ: 'Argelia',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egipto',
    EH: 'Sáhara Occidental',
    ER: 'Eritrea',
    ES: 'España',
    ET: 'Etiopía',
    FI: 'Finlandia',
    FJ: 'Fiyi',
    FK: 'Islas Malvinas',
    FM: 'Micronesia',
    FO: 'Islas Feroe',
    FR: 'Francia',
    GA: 'Gabón',
    GB: 'Reino Unido',
    GD: 'Granada',
    GE: 'Georgia',
    GF: 'Guayana Francesa',
    GG: 'Guernesey',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GL: 'Groenlandia',
    GM: 'Gambia',
    GN: 'Guinea',
    GP: 'Guadalupe',
    GQ: 'Guinea Ecuatorial',
    GR: 'Grecia',
    GS: 'Islas Georgia del Sur y Sandwich del Sur',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Guinea-Bisáu',
    GY: 'Guyana',
    HK: 'RAE de Hong Kong (China)',
    HM: 'Islas Heard y McDonald',
    HN: 'Honduras',
    HR: 'Croacia',
    HT: 'Haití',
    HU: 'Hungría',
    ID: 'Indonesia',
    IE: 'Irlanda',
    IL: 'Israel',
    IM: 'Isla de Man',
    IN: 'India',
    IO: 'Territorio Británico del Océano Índico',
    IQ: 'Irak',
    IR: 'Irán',
    IS: 'Islandia',
    IT: 'Italia',
    JE: 'Jersey',
    JM: 'Jamaica',
    JO: 'Jordania',
    JP: 'Japón',
    KE: 'Kenia',
    KG: 'Kirguistán',
    KH: 'Camboya',
    KI: 'Kiribati',
    KM: 'Comoras',
    KN: 'San Cristóbal y Nieves',
    KP: 'Corea del Norte',
    KR: 'Corea del Sur',
    KW: 'Kuwait',
    KY: 'Islas Caimán',
    KZ: 'Kazajistán',
    LA: 'Laos',
    LB: 'Líbano',
    LC: 'Santa Lucía',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesoto',
    LT: 'Lituania',
    LU: 'Luxemburgo',
    LV: 'Letonia',
    LY: 'Libia',
    MA: 'Marruecos',
    MC: 'Mónaco',
    MD: 'Moldavia',
    ME: 'Montenegro',
    MF: 'San Martín',
    MG: 'Madagascar',
    MH: 'Islas Marshall',
    MK: 'Macedonia del Norte',
    ML: 'Mali',
    MM: 'Myanmar (Birmania)',
    MN: 'Mongolia',
    MO: 'RAE de Macao (China)',
    MP: 'Islas Marianas del Norte',
    MQ: 'Martinica',
    MR: 'Mauritania',
    MS: 'Montserrat',
    MT: 'Malta',
    MU: 'Mauricio',
    MV: 'Maldivas',
    MW: 'Malaui',
    MX: 'México',
    MY: 'Malasia',
    MZ: 'Mozambique',
    NA: 'Namibia',
    NC: 'Nueva Caledonia',
    NE: 'Níger',
    NF: 'Isla Norfolk',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Países Bajos',
    NO: 'Noruega',
    NP: 'Nepal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'Nueva Zelanda',
    OM: 'Omán',
    PA: 'Panamá',
    PE: 'Perú',
    PF: 'Polinesia Francesa',
    PG: 'Papúa Nueva Guinea',
    PH: 'Filipinas',
    PK: 'Pakistán',
    PL: 'Polonia',
    PM: 'San Pedro y Miquelón',
    PN: 'Islas Pitcairn',
    PR: 'Puerto Rico',
    PS: 'Territorios Palestinos',
    PT: 'Portugal',
    PW: 'Palaos',
    PY: 'Paraguay',
    QA: 'Catar',
    RE: 'Reunión',
    RO: 'Rumanía',
    RS: 'Serbia',
    RU: 'Rusia',
    RW: 'Ruanda',
    SA: 'Arabia Saudí',
    SB: 'Islas Salomón',
    SC: 'Seychelles',
    SD: 'Sudán',
    SE: 'Suecia',
    SG: 'Singapur',
    SH: 'Santa Elena',
    SI: 'Eslovenia',
    SJ: 'Svalbard y Jan Mayen',
    SK: 'Eslovaquia',
    SL: 'Sierra Leona',
    SM: 'San Marino',
    SN: 'Senegal',
    SO: 'Somalia',
    SR: 'Surinam',
    SS: 'Sudán del Sur',
    ST: 'Santo Tomé y Príncipe',
    SV: 'El Salvador',
    SX: 'Sint Maarten',
    SY: 'Siria',
    SZ: 'Esuatini',
    TC: 'Islas Turcas y Caicos',
    TD: 'Chad',
    TF: 'Territorios Australes Franceses',
    TG: 'Togo',
    TH: 'Tailandia',
    TJ: 'Tayikistán',
    TK: 'Tokelau',
    TL: 'Timor-Leste',
    TM: 'Turkmenistán',
    TN: 'Túnez',
    TO: 'Tonga',
    TR: 'Turquía',
    TT: 'Trinidad y Tobago',
    TV: 'Tuvalu',
    TW: 'Taiwán',
    TZ: 'Tanzania',
    UA: 'Ucrania',
    UG: 'Uganda',
    UM: 'Islas menores alejadas de EE. UU.',
    US: 'Estados Unidos',
    UY: 'Uruguay',
    UZ: 'Uzbekistán',
    VA: 'Ciudad del Vaticano',
    VC: 'San Vicente y las Granadinas',
    VE: 'Venezuela',
    VG: 'Islas Vírgenes Británicas',
    VI: 'Islas Vírgenes de EE. UU.',
    VN: 'Vietnam',
    VU: 'Vanuatu',
    WF: 'Wallis y Futuna',
    WS: 'Samoa',
    YE: 'Yemen',
    YT: 'Mayotte',
    ZA: 'Sudáfrica',
    ZM: 'Zambia',
    ZW: 'Zimbabue',
  },
  fr: {
    AD: 'Andorre',
    AE: 'Émirats arabes unis',
    AF: 'Afghanistan',
    AG: 'Antigua-et-Barbuda',
    AI: 'Anguilla',
    AL: 'Albanie',
    AM: 'Arménie',
    AO: 'Angola',
    AQ: 'Antarctique',
    AR: 'Argentine',
    AS: 'Samoa américaines',
    AT: 'Autriche',
    AU: 'Australie',
    AW: 'Aruba',
    AX: 'Îles Åland',
    AZ: 'Azerbaïdjan',
    BA: 'Bosnie-Herzégovine',
    BB: 'Barbade',
    BD: 'Bangladesh',
    BE: 'Belgique',
    BF: 'Burkina Faso',
    BG: 'Bulgarie',
    BH: 'Bahreïn',
    BI: 'Burundi',
    BJ: 'Bénin',
    BL: 'Saint-Barthélemy',
    BM: 'Bermudes',
    BN: 'Brunei',
    BO: 'Bolivie',
    BQ: 'Pays-Bas caribéens',
    BR: 'Brésil',
    BS: 'Bahamas',
    BT: 'Bhoutan',
    BV: 'Île Bouvet',
    BW: 'Botswana',
    BY: 'Biélorussie',
    BZ: 'Belize',
    CA: 'Canada',
    CC: 'Îles Cocos',
    CD: 'Congo-Kinshasa',
    CF: 'République centrafricaine',
    CG: 'Congo-Brazzaville',
    CH: 'Suisse',
    CI: 'Côte d’Ivoire',
    CK: 'Îles Cook',
    CL: 'Chili',
    CM: 'Cameroun',
    CN: 'Chine',
    CO: 'Colombie',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CV: 'Cap-Vert',
    CW: 'Curaçao',
    CX: 'Île Christmas',
    CY: 'Chypre',
    CZ: 'Tchéquie',
    DE: 'Allemagne',
    DJ: 'Djibouti',
    DK: 'Danemark',
    DM: 'Dominique',
    DO: 'République dominicaine',
    DZ: 'Algérie',
    EC: 'Équateur',
    EE: 'Estonie',
    EG: 'Égypte',
    EH: 'Sahara occidental',
    ER: 'Érythrée',
    ES: 'Espagne',
    ET: 'Éthiopie',
    FI: 'Finlande',
    FJ: 'Fidji',
    FK: 'Îles Malouines',
    FM: 'Micronésie',
    FO: 'Îles Féroé',
    FR: 'France',
    GA: 'Gabon',
    GB: 'Royaume-Uni',
    GD: 'Grenade',
    GE: 'Géorgie',
    GF: 'Guyane française',
    GG: 'Guernesey',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GL: 'Groenland',
    GM: 'Gambie',
    GN: 'Guinée',
    GP: 'Guadeloupe',
    GQ: 'Guinée équatoriale',
    GR: 'Grèce',
    GS: 'Géorgie du Sud-et-les Îles Sandwich du Sud',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Guinée-Bissau',
    GY: 'Guyana',
    HK: 'R.A.S. chinoise de Hong Kong',
    HM: 'Îles Heard-et-MacDonald',
    HN: 'Honduras',
    HR: 'Croatie',
    HT: 'Haïti',
    HU: 'Hongrie',
    ID: 'Indonésie',
    IE: 'Irlande',
    IL: 'Israël',
    IM: 'Île de Man',
    IN: 'Inde',
    IO: 'Territoire britannique de l’océan Indien',
    IQ: 'Irak',
    IR: 'Iran',
    IS: 'Islande',
    IT: 'Italie',
    JE: 'Jersey',
    JM: 'Jamaïque',
    JO: 'Jordanie',
    JP: 'Japon',
    KE: 'Kenya',
    KG: 'Kirghizstan',
    KH: 'Cambodge',
    KI: 'Kiribati',
    KM: 'Comores',
    KN: 'Saint-Christophe-et-Niévès',
    KP: 'Corée du Nord',
    KR: 'Corée du Sud',
    KW: 'Koweït',
    KY: 'Îles Caïmans',
    KZ: 'Kazakhstan',
    LA: 'Laos',
    LB: 'Liban',
    LC: 'Sainte-Lucie',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesotho',
    LT: 'Lituanie',
    LU: 'Luxembourg',
    LV: 'Lettonie',
    LY: 'Libye',
    MA: 'Maroc',
    MC: 'Monaco',
    MD: 'Moldavie',
    ME: 'Monténégro',
    MF: 'Saint-Martin',
    MG: 'Madagascar',
    MH: 'Îles Marshall',
    MK: 'Macédoine du Nord',
    ML: 'Mali',
    MM: 'Myanmar (Birmanie)',
    MN: 'Mongolie',
    MO: 'R.A.S. chinoise de Macao',
    MP: 'Îles Mariannes du Nord',
    MQ: 'Martinique',
    MR: 'Mauritanie',
    MS: 'Montserrat',
    MT: 'Malte',
    MU: 'Maurice',
    MV: 'Maldives',
    MW: 'Malawi',
    MX: 'Mexique',
    MY: 'Malaisie',
    MZ: 'Mozambique',
    NA: 'Namibie',
    NC: 'Nouvelle-Calédonie',
    NE: 'Niger',
    NF: 'Île Norfolk',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Pays-Bas',
    NO: 'Norvège',
    NP: 'Népal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'Nouvelle-Zélande',
    OM: 'Oman',
    PA: 'Panama',
    PE: 'Pérou',
    PF: 'Polynésie française',
    PG: 'Papouasie-Nouvelle-Guinée',
    PH: 'Philippines',
    PK: 'Pakistan',
    PL: 'Pologne',
    PM: 'Saint-Pierre-et-Miquelon',
    PN: 'Îles Pitcairn',
    PR: 'Porto Rico',
    PS: 'Territoires palestiniens',
    PT: 'Portugal',
    PW: 'Palaos',
    PY: 'Paraguay',
    QA: 'Qatar',
    RE: 'La Réunion',
    RO: 'Roumanie',
    RS: 'Serbie',
    RU: 'Russie',
    RW: 'Rwanda',
    SA: 'Arabie saoudite',
    SB: 'Îles Salomon',
    SC: 'Seychelles',
    SD: 'Soudan',
    SE: 'Suède',
    SG: 'Singapour',
    SH: 'Sainte-Hélène',
    SI: 'Slovénie',
    SJ: 'Svalbard et Jan Mayen',
    SK: 'Slovaquie',
    SL: 'Sierra Leone',
    SM: 'Saint-Marin',
    SN: 'Sénégal',
    SO: 'Somalie',
    SR: 'Suriname',
    SS: 'Soudan du Sud',
    ST: 'Sao Tomé-et-Principe',
    SV: 'Salvador',
    SX: 'Saint-Martin (partie néerlandaise)',
    SY: 'Syrie',
    SZ: 'Eswatini',
    TC: 'Îles Turques-et-Caïques',
    TD: 'Tchad',
    TF: 'Terres australes françaises',
    TG: 'Togo',
    TH: 'Thaïlande',
    TJ: 'Tadjikistan',
    TK: 'Tokelau',
    TL: 'Timor oriental',
    TM: 'Turkménistan',
    TN: 'Tunisie',
    TO: 'Tonga',
    TR: 'Turquie',
    TT: 'Trinité-et-Tobago',
    TV: 'Tuvalu',
    TW: 'Taïwan',
    TZ: 'Tanzanie',
    UA: 'Ukraine',
    UG: 'Ouganda',
    UM: 'Îles mineures éloignées des États-Unis',
    US: 'États-Unis',
    UY: 'Uruguay',
    UZ: 'Ouzbékistan',
    VA: 'État de la Cité du Vatican',
    VC: 'Saint-Vincent-et-les Grenadines',
    VE: 'Venezuela',
    VG: 'Îles Vierges britanniques',
    VI: 'Îles Vierges des États-Unis',
    VN: 'Viêt Nam',
    VU: 'Vanuatu',
    WF: 'Wallis-et-Futuna',
    WS: 'Samoa',
    YE: 'Yémen',
    YT: 'Mayotte',
    ZA: 'Afrique du Sud',
    ZM: 'Zambie',
    ZW: 'Zimbabwe',
  },
};
